import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
<<<<<<< HEAD
import { ClerkProvider } from '@clerk/nextjs'
import { ModalProvider } from '@/providers/modal-provider'

=======
>>>>>>> 6c31ebd (Initial commit from Create Next App)

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
<<<<<<< HEAD
  title: 'Admin Dashboard',
  description: 'Admin Dashboard',
=======
  title: 'Create Next App',
  description: 'Generated by create next app',
>>>>>>> 6c31ebd (Initial commit from Create Next App)
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
<<<<<<< HEAD
      <ClerkProvider>
        <html lang="en">
          <body className={inter.className}>
            <ModalProvider/>
            {children}
            </body>
        </html>
      </ClerkProvider>
=======
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
>>>>>>> 6c31ebd (Initial commit from Create Next App)
  )
}
